### ISSUE TITLE
How can I control Hint Context ?

### ISSUE THREAD

**Issue by engrmkchow** [ogobrecht/apex-plugin-dhtmlx-gantt#10]
How can I control Hint Context ?

**Comment by ogobrecht** [comment]
Hi engrmkchow,

is this really your question? Can you please give more details? Otherwise I am not able to answer your question. A good place to start is to have a look at the vendor documentation: https://docs.dhtmlx.com/gantt/

Kind regards
Ottmar

**Comment by engrmkchow** [comment]
Dear Ottmar,
  Thank you very much. I have used Gantt Plugin in my production. 
  Now, working on TreeGrid by Alexander Warkus , having some problem with making Link on it.


Regards
Khalequzzaman

Sent from Mail for Windows 10

**Comment by ogobrecht** [comment]
Hi again,

sorry engrmkchow, but without any details you are wasting my free time - "having some problem with making Link on it" is NOT a detailed description of what you are trying to do, what behaviour you are expecting and how the system is responding to your action. It is not clear if you try to create a link from the Gantt plug-in to the tree grid or vice versa. Also, please provide links where possible, screenshots, code snippets, whatever you think will help me to understand your problem.

You can always come back to me with more details - but please expect no more answers when you don't put more energy in your question than 5 seconds of finger gymnastic.

Kind regards
Ottmar

**Comment by engrmkchow** [comment]
Dear Ottmar,
  Thank you very much for reply. It would better if we get below three
facilities in your Plugin .
     1. User Define Calendar Start Date
     2. Separate Task Description  column ,Default it is coming from task
name
     3. Separate Hint  Column , default  it is coming from task,start
date,end date


Regards
Khalequzzaman

**Comment by ogobrecht** [comment]
No valuable feedback. Issue closed.
