### ISSUE TITLE
Task_id data type

### ISSUE THREAD

**Issue by flunanica** [ogobrecht/apex-plugin-dhtmlx-gantt#12]
Thank you for the plugin, it have helped me a lot. However,I have encountered a small problem with my use of the pluggin. My task_ids are varchar values, but given that the task_id for the plugin seems to be number i am having trouble with the links between tasks. I have 010 as an task_id which the pluggin returns as 10.
I would greatly appreciete if you could give me a hint where i could change this variable data type.

**Comment by ogobrecht** [comment]
Hi lunanica,

this could be considered a bug. I seem to have been so stupid to think the whole world would use numbers as ID's - although this is good practice, there are also use cases for strings...

In short, I've changed the internal handling of the plug-in JavaScript helper function to leave the ID's untouched. Should work now - if not, please let me know.

You can download the latest version [here](https://github.com/ogobrecht/apex-plugin-dhtmlx-gantt/releases/latest).

Best regards
Ottmar

**Comment by flunanica** [comment]
Hi Ottmar, 
I just tried the new version and it works perfectly! I greatly appreciate the time you spend on this update.

I will keep playing with the plugin, I am build more features on top of it. I will let you know if something else comes up that can be of use to others. 
If anyone needs help with it, I am at his or her services. 

Best regards,
Fernando

**Comment by ogobrecht** [comment]
Hi Fernando,

nice to here that it is now working for you. I close therefore this issue. If you have other suggestions or ideas in the future feel free to open new issues :-)

Best regards
Ottmar

**Comment by flunanica** [comment]
Perfect Ottmar,
I will be in touch
Just a question, issues are supposed to be closes by me? If i was supposed
to close it, sorry i wont forget next time.

**Comment by ogobrecht** [comment]
Hi Fernando,

no problem - issues can be closed by the creator or all people with write access to the repository - in this case currently only me. It doesn't matter who is closing the issue :-)

Best regards
Ottmar
