### ISSUE TITLE
Your data string is not starting with "<" or "{" - parsing not possible

### ISSUE THREAD

**Issue by darshanputtaswamy** [ogobrecht/apex-plugin-dhtmlx-gantt#13]
Hi, 

I was exploring this plugin and ran into below issue. 

When I run the query through sql developer, I get Below data, I don't see any issue with start_date format ( I have ensure to maintain the format as per plugin it is in 'YYYY-MM-DD').

`<data> <task id="65" text="[L2] Improve Level 2" start_date="2019-06-09" progress="1" duration="2448" open="true"/> <task id="66" text="[L3] Improve 3" start_date="2019-06-11" progress="1" duration="2424" open="true"/> <task id="41" text="[L2] Testing Testing" start_date="2018-10-24" progress="1" duration="2184" open="true"/> <task id="67" text="[L2] Improve L2" start_date="2018-10-26" progress="1" duration="2616" open="true"/> </data>
`
But rendering fails with error 

`

> plugin-dhtmlxgantt-helper.min.js:6 Plugin dhtmlxGantt: Your data string is not starting with "<" or "{" - parsing not possible

`

Below is the state of 	plugin_dhtmlxGantt

```
**chartContainerId: "R982564392191016441_dhtmlxGantt"
chartContainerIdElement: n.fn.init [div#R982564392191016441_dhtmlxGantt, context: document, selector: "#R982564392191016441_dhtmlxGantt"]
dataRaw: "ORA-01843: not a valid month"**

```
Not sure why I get ORA-01843: not a valid month only while rendering the rows

**Comment by ogobrecht** [comment]
Hi,

your data seems to be ok. As described [here](https://github.com/ogobrecht/apex-plugin-dhtmlx-gantt#example-query) the query must return a single CLOB result - this means the plug-in tries to read the first row, first column. If your data is in the second column this is useless for the plugin, as the first column, first row is delivered to the frontend regardless of the name of the column.

So, your data seems to be correct - but I assume it is not in the first column of your query, right?

If I am wrong please provide me an example app on apex.oracle.com with the error and developer access to the workspace, so I am able to digg into the problem.

If I am right, please close the issue by yourself or let me know and I will close the issue.

Hope my answer is helpful, best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi,

any news? Is your problem solved? Can I close the issue?

Best regards
Ottmar

**Comment by ogobrecht** [comment]
As there is no further feedback from the user I close the issue now.
