### ISSUE TITLE
Reduced version vs. Pro version ?

### ISSUE THREAD

**Issue by jzzh** [ogobrecht/apex-plugin-dhtmlx-gantt#14]
What exactly are the features missing in the reduced version?
How much is the pro version ?

**Comment by ogobrecht** [comment]
Hi Jochen,

thank you for your question and sorry for my late response. I have updated the project README to reflect my answer. You can have a look here on the vendor site: 

- https://docs.dhtmlx.com/gantt/desktop__editions_comparison.html
- https://dhtmlx.com/docs/products/dhtmlxGantt/#licensing

Please note that I have nothing to do with the vendor of the library. The plugin uses v4.1.0 of the library. In the meantime the vendor has released the version 6. If you can't wait for an plugin update (I need to find time), you can try to upload the new files into the plugin or even better download the current plugin files, place it onto your webserver and overwrite the files there with the new ones. Please be careful to not overwrite the plugin specific files. If you have trouble, please let me know - I have not tested yet the new version.

There is also some information in the online help of the application builder when you use the plugin. I recommend to install the sample application first ([latest release](https://github.com/ogobrecht/apex-plugin-dhtmlx-gantt/releases/latest)) and see, how the plugin is used.

Hope my answer is helpful for you, best regards
Ottmar

<img width="951" alt="gantt-version" src="https://user-images.githubusercontent.com/10425445/51926335-5a43e400-23f1-11e9-92a3-5a1b8eefbb04.png">
<img width="1275" alt="gantt-attributes" src="https://user-images.githubusercontent.com/10425445/51926336-5adc7a80-23f1-11e9-9f31-067b9cecd34f.png">
