### ISSUE TITLE
Can we add a milestone type? 

### ISSUE THREAD

**Issue by shiaohuihoh** [ogobrecht/apex-plugin-dhtmlx-gantt#18]
Hi,

I would like to check if we can add a milestone type to the gantt chart?
Or can we take away the timeline for project task?
I've changed the duration to 0, but it auto-populate a value to the duration in the chart.

Thank you in advance.

**Comment by ogobrecht** [comment]
Hi,

unfortunately milestones are only available in the PRO version. See the docs [here](https://docs.dhtmlx.com/gantt/desktop__milestones.html) and [here](https://docs.dhtmlx.com/gantt/desktop__editions_comparison.html).

I already stated this in the project README:

>* Based on [dhtmlxGantt](https://dhtmlx.com/docs/products/dhtmlxGantt/) ([docs](http://docs.dhtmlx.com/gantt/)) library (v4.1.0, newer version available from the vendor)
>    * This is the GPLv2 version of the library with a reduced set of functions
>        * [Compare the free and the Pro version](https://docs.dhtmlx.com/gantt/desktop__editions_comparison.html)
>    * If you need all functionality you can buy the Pro version and copy the Pro files into the plugin
>    * I was asked to create this plugin and I have nothing to do with the company DHTMLX, so please do not complain ;-)

For the second question: Can you please give more details? A screenshot what you have currently and what you want to achive? Some sample data or a copy of the demo app with a running page showing your problem on apex.oracle.com?

Thank you and best regards\
Ottmar

**Comment by shiaohuihoh** [comment]
Hi Ottmar,

Thank you for your reply.

Thanks.

**Comment by ogobrecht** [comment]
Close issue because no feedback since April.
