### ISSUE TITLE
defining rtl direction of the gant

### ISSUE THREAD

**Issue by Dgil4313** [ogobrecht/apex-plugin-dhtmlx-gantt#19]
Hello,
I wanted to know how to convert dynamically according to parameter the direction of the gant

I tried to use
gantt.config.rtl = true;
gantt.config.layout = {
    css: "gantt_container",
    rows: [
        {
            cols: [
                {view: "scrollbar", id: "scrollVer"},
                {view: "timeline", scrollX: "scrollHor", scrollY: "scrollVer"},
                {resizer: true, width: 1},
                {view: "grid", scrollX: "scrollHor", scrollY: "scrollVer"}
            ]
        },
        {view: "scrollbar", id: "scrollHor", height: 20}
    ]
};
but nothing is happen
we payed for the comercial version
i have the last one (9)
but how the plugin can work with this version?

Thank you

**Comment by ogobrecht** [comment]
Hi,

the current plug-in version is based on the gantt library version 4.1.0. If I get it right from the gantt library docs then the RTL functionality was introduced in the library version 5.1.0 - current library version is 7.0.10.

So, it seems that I need to update the plug-in to the latest library version. Anyway, if you have payed for the pro version of the library you have to copy over your downloaded pro library files by yourself into the plug-in or to your webserver in the case you redirect the plug-in files. As there are multiple major versions between 4.1.0 and 7.0.0 there is no guaranty that this will work without problems.

If you have a little bit of plug-in development experience then you should be able to manage this upgrade by yourself. If not, I will try to update the plug-in soon. Please let me know your progress.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Close issue since this is now working with the latest release.
