### ISSUE TITLE
Split task

### ISSUE THREAD

**Issue by aspcsharp9** [ogobrecht/apex-plugin-dhtmlx-gantt#23]
Hello,

Nice plugin for Oracle Apex good job, is it possible in your plugin split task in one row? 

eg. https://snippet.dhtmlx.com/5/d58b20da5

![split](https://user-images.githubusercontent.com/15157982/105677936-cf692780-5eec-11eb-817d-e6650a69fbd2.jpg)

**Comment by ogobrecht** [comment]
Hi,

I checked [the docs](https://docs.dhtmlx.com/gantt/desktop__split_tasks.html) - this functionality is available in the PRO edition only. So, I cannot test it. But it should work as you only need to  provide a new attribute in the query - here an example from the demo app (delivering XML data, see last line attribute render):
`case when t_id = 4 then 'split' else null end as "render",`
![image](https://user-images.githubusercontent.com/10425445/105858554-bdba7980-5feb-11eb-9833-44b39cf0d67a.png)

You can see then in the browser console the parsed data:
`plugin_dhtmlxGantt.dataParsed`
![image](https://user-images.githubusercontent.com/10425445/105858941-37526780-5fec-11eb-90dc-d781533d150e.png)

You can essentially use everything from the Gantt library when you have the pro version. Most times you need to provide more attributes in the data and you need also to provide JavaScript code to handle your special use cases. This is a little bit like it is with the Interactive Grid. The limits are your JavaScript skills. The plug-in provides you three entry points for your JavaScript code in the region attributes. If this is not enough you can use dynamic actions or provide your code in files...

Hope this answers your question

Best regards
Ottmar
