### ISSUE TITLE
Oracle Apex Saving

### ISSUE THREAD

**Issue by mikedavidson1959blue** [ogobrecht/apex-plugin-dhtmlx-gantt#25]
Hi Ottmar,

I have just started evaluating DHTMLX Gantt and so far I am very very impressed. I am considering integrating the Gantt chart component into my - about to be launched and it's an Oracle Apex app - but was wondering how saving of data was implemented. As you can appreciated saving can possibly be the slowest task so I wanted to know if there was anything built into DHTMLX Gantt to optimize this process and if so, do you have any Apex example of how this could be/is implemented in Apex? I am currently using Oracle Apex 20.1 about to upgrade to 21.1.

Really looking forward to hearing back and thankyou so far for the excellent plugin.

Yours,

Mike Davidson
www.cConix.com

**Comment by ogobrecht** [comment]
Hi Mike,

please download and install the demo app. You can find it attached to the latest release. Then inspect the implementation and look, how the modal edit windows are opened. The plug-in does not use the edit modals from the Gantt library. Instead you define the links to the APEX edit pages in the region query for your data. These links are then used by the plug-in when a node or link is clicked. This ensures that you can use standard APEX pages to edit your data. Please have also a look at the dynamic actions int the app. Some links are build at runtime…

Hope this helps. If not, please let me know…

Best regards
Ottmar

**Comment by mikedavidson1959blue** [comment]
Hi Ottmar,

Thank you very much for the update email.

I have already done as you described. I've imported the sample app and then implemented the code in my own app, as I say I am very impressed with what you have done. In my app I am now able to launch Gantt with my own data, I have also converted the pop-up pages so everything looks great.

My main questions are (and these are possibly a version issues):


  1.   I tried to change the calendar ribbon to show Months on row one and Weeks on row two by adding the following code into the 'before init js code'. However, when I run the page the calendar there is only a single calendar ribbon showing dates in DD Mon format (i.e. 01 Jan, 02 Jan ...). My code is:

gantt.templates.tooltip_text = function(start, end, task) {
    return "<b>Task:</b> " + task.text + "<br/>" +
           "<b>Start date:</b> " + gantt.templates.tooltip_date_format(start) + "<br/>" +
           "<b>End date:</b> " + gantt.templates.tooltip_date_format(end);
};

gantt.config.scales = [
    {unit: "month", step: 1, format: "%F, %Y"},
    {unit: "day", step: 1, format: "%j, %D"}
];


  1.  When I download the new JS files for the latest PRO version form the DMTML website do I need to replace all of the JS files associated with plug-in or only some of them

  1.  Finally, once I get the forward/backward pass scheduling to work in the app, do you know what would be the best way to save the calculated early start, early finish, late start, late finish dates etc. back to the database? Is there an event that I can build in to detect the end of forward/backward pass process? Would you suggest this event doing a simple update at the DB level or alternatively posting the resulting data in XML format back to an Apex ajax process or the DHTML server?

I appreciate that some of these questions are not related to your plug-in, but I just looking for advice as I continue my evaluation process.

Yours,



[horizontal bar]
Mike Davidson
cConix, CEO
[cConix]

Landline - (1) 403-538-3196
Mobile - (1) 403-629-4009
email - ***@***.***

Suite 300, 840 6th Avenue SW
Calgary, Alberta T2P 3E5

http://www.cConix.com<http://www.cconix.com/>


________________________________

**Comment by ogobrecht** [comment]
Hi Mike,

sorry for the late answer. 

> 1.   I tried to change the calendar ribbon...

I have no idea why this is not working - I use the exactly same code in my example app and it works. Can you please tell me if you have already copied over the pro version of the library and if so, which library version you copied over?

> 1.  When I download the new JS files for the latest PRO version...

I would replace all of them. I know, there are many, but you can speed up the upload process by providing a zipped version of the new files (in the needed directory structure). APEX is capable of unzipping your new files. An other way would be to provide the files on the web server (if you have access to it) and provide your server URL in the plug-in files section.

> 1.  Finally, once I get the forward/backward pass scheduling to work...

As I don't have the pro version I can only argue here: I would try to use the [onAfterAutoSchedule](https://docs.dhtmlx.com/gantt/api__gantt_onafterautoschedule_event.html) event and save the data with an dynamic action. Also see the [auto scheduling article](https://docs.dhtmlx.com/gantt/desktop__auto_scheduling.html) and [the full list of events in the Gantt API docs](https://docs.dhtmlx.com/gantt/api__refs__gantt_events.html)

Hope this helps, best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Mike,

hope you are doing well. I will close this issue now because of inactivity. Feel free to reopen it.
