### ISSUE TITLE
Update Start Date

### ISSUE THREAD

**Issue by abdoonabil** [ogobrecht/apex-plugin-dhtmlx-gantt#26]
Hello,
Thanks for this Awesome Plugin 
Just need little help in updating start date by drag the task
can you help me please ?

**Comment by ogobrecht** [comment]
Hi,

please install the demo app - it is attached to the [latest release](https://github.com/ogobrecht/apex-plugin-dhtmlx-gantt/releases/latest). Then inspect how this was implemented in the demo app.

Hope this helps. If not, please let me know...

Best regards
Ottmar

**Comment by abdoonabil** [comment]
Thanks for response
Demo app is working perfect 
But I had to change pages numbers, tables and query
That's why I don't know where to update the links or scripts 

I'm getting nothing when try to put new date after drag the task
also can't execute this:

:p17_url := apex_util.prepare_url(
    p_url                    => 'f?p='
        ||  :app_id
        ||  ':7:'
        ||  :app_session
        ||  ':::2:P7_ID,P7_DATETIME,P7_PROG:'
        ||  :P17_TASK_ID || ','
        ||  :P17_TASK_START_DATE || ','
        ||  :P17_TASK_PROGRESS,
        p_triggering_element => 'apex.jQuery("#my_gantt")'
    );

    begin
    update EV_Task
       set datetime = to_date(:APEX$P17_TASK_START_DATE, 'YYYYMMDDHH24MISS')
         
     where id = :P17_TASK_ID;
end;

Regards

**Comment by ogobrecht** [comment]
Hi,

please have a look at the dynamic actions in the demo app - in the screenshot below you see that for the task drag event three actions are executed:

1. JavaScript: Get the relevant data out of the event and save it in page items
    ```js
    $s('P1_TASK_ID', this.data.task.id);
    $s('P1_TASK_START_DATE', plugin_dhtmlxGantt.util_toLocalIsoString(this.data.task.start_date).substring(0, 10));
    $s('P1_TASK_DURATION', this.data.task.duration.toString());
    $s('P1_TASK_PROGRESS', plugin_dhtmlxGantt.util_round(this.data.task.progress, 1).toString());
    ```
2. PL/SQL: Construct the URL to open the Task with the changed data from the event
    ```sql
    :p1_url := apex_util.prepare_url(
        p_url                    => 'f?p='
            ||  :app_id
            ||  ':2:'
            ||  :app_session
            ||  ':::2:P2_T_ID,P2_T_START_DATE,P2_T_DURATION,P2_T_PROGRESS:'
            ||  :P1_TASK_ID || ','
            ||  :P1_TASK_START_DATE || ','
            ||  :P1_TASK_DURATION || ','
            ||  :P1_TASK_PROGRESS,
            p_triggering_element => 'apex.jQuery("#my_gantt")'
        );    ```
3. JavaScript: Call the URL - means open the task in a modal dialog with the changed data
    ```js
    plugin_dhtmlxGantt.util_openUrl( $v('P1_URL') );
    ```

![image](https://user-images.githubusercontent.com/10425445/139396307-afce3cf3-a0aa-4a2b-8a4b-9abef2f7d94f.png)

The whole idea of the plug-in ist to integrate the Gantt JavaScript library and to expose relevant events to be able to use standard APEX modal dialogs to edit the tasks. The downside of this is, that you need to work with the event data to open your modal dialogs and that you need to prepare your URLs somewhere. You can prepare the edit URLs beforhand in the region SQL, but when you change data and you would like to open the modal dialog with the already changed data you need to prepare the URL with the data you want to bring into the modal dialog. That is the reason why we prepare the URL with a dynamic action...

Hope this helps... please let me know...

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi again,

hope you are doing well. I will close this issue now because of inactivity. Feel free to reopen it.
