### ISSUE TITLE
Task Coloro

### ISSUE THREAD

**Issue by mappo1980** [ogobrecht/apex-plugin-dhtmlx-gantt#28]
Hi Ottmar Gobrecht, could you tell me if it is possible to change the colors of the tasks?
Thank you

**Comment by ogobrecht** [comment]
Hi mappo1980,

as described in the README, please have a look in the docs of the vendor of the library. First of all you can declarative set the skin in the region settings. If you need more fine grained control over the styling, then have a look in the vendor docs:

- [Available Skins](https://docs.dhtmlx.com/gantt/desktop__skins.html)
- [CSS Documentation](https://docs.dhtmlx.com/gantt/desktop__css_overview.html)

Hope this helps

**Comment by mappo1980** [comment]
CIao ogobrecht, thanks for the reply, I have seen this wiki
Task text templates and custom markers, but it doesn't work

I should color the TASKs based on one condition

it's possible?

**Comment by ogobrecht** [comment]
Hi mappo1980,

In short: Yes, it is possible.

A little bit longer: you can always bring in own attributes to your tasks and links - simply add your own attributes/columns to the SQL query. In Javascript you can access then your custom attributes on a task with the JSON dot notation and use them to conditionally add custom classes or styles to your task HTML code through the templates.

Hope this helps.
