### ISSUE TITLE
Auto scheduling

### ISSUE THREAD

**Issue by nbao** [ogobrecht/apex-plugin-dhtmlx-gantt#29]
Hello, 
i have question please.
Does auto scheduling work? if yes How do I add config for auto schedule? Sometimes the task name is very long, how can I increase the width of the left window?
Thanks

**Comment by ogobrecht** [comment]
Hi, as described on the project page, you need to use the library's extensive JavaScript API for anything that is not available as declarative region attributes. Please consult the library's documentation and take a look at the sample application provided. The JavaScript API is very extensive and it is therefore impossible to create a plug-in that meets all the requirements...
