### ISSUE TITLE
Support for Printing...

### ISSUE THREAD

**Issue by GasparYYC** [ogobrecht/apex-plugin-dhtmlx-gantt#3]
Not a bug, enhancement request.

Apparently it's very easy to add printing via export.. 
https://docs.dhtmlx.com/gantt/desktop__export.html#exporttopdf

or even this:
http://www.thisisit4u.eu/gantt/docsExplorer/dhtmlxgantt/dhtmlxgantt___api_method_dhtmlxganttchart_printtowindow.html

Although its based on a paid service (or reports show a watermark) it would be great if the plug in does the call to enable printing.

thanks for your consideration

**Comment by ogobrecht** [comment]
Hi @GasparYYC,

I was thinking a while about your printing request. At the end I have to say, that I don't like the idea to load additional libs from the internet and allow per default to post data to an internet service. May be someone does this per accident and post sensitive data. If you or someone else need this printing/export functionality it is fairly easy to implement it by yourself directly on your page.

Sorry for refuse your request. Hope, it is ok for you.

Best regards
Ottmar
