### ISSUE TITLE
Hours management

### ISSUE THREAD

**Issue by mappo1980** [ogobrecht/apex-plugin-dhtmlx-gantt#30]
Hi, I should manage the hours on the gant
I would like to set the duration in hours, what can I do?

![Immagine 2022-10-14 080442](https://user-images.githubusercontent.com/10465501/195773957-bdd6d68e-5c3b-4666-95ee-916e556f1d09.png)

**Comment by ogobrecht** [comment]
Hi, as described on the project page, you need to use the library's extensive JavaScript API for anything that is not available as declarative region attributes. Please consult the library's documentation and take a look at the sample application provided. The JavaScript API is very extensive and it is therefore impossible to create a plug-in that meets all the requirements...
