### ISSUE TITLE
How can we upgrade its dhtmlx library by ourself

### ISSUE THREAD

**Issue by shabbir395** [ogobrecht/apex-plugin-dhtmlx-gantt#35]
Thanks Ottmar for this fantastic work.
Is there a way that we can upgrade its dhtmlx library by ourself? 
please guide us

**Comment by jzzh** [comment]
I just upgaded to dhtmlx gantt 8.0.6

Go to Plug-in: dhtmlxGantt - Files
Download Files as zip
Unzip the downloaded archive and replace all files with the new version files
Make sure not to delete
 - plugin-dhtmlxgantt-helper.min.js 
 - plugin-dhtmlxgantt-helper.js

Make a new zip containing
 Folder dhtmlxgantt with the new version sources
 File plugin-dhtmlxgantt-helper.min.js 
 File plugin-dhtmlxgantt-helper.js

Delete all Files in the Plugin !

Create File > Use your zip archive

**Comment by ogobrecht** [comment]
Thanks for the answer, Jochen. I had simply overseen the notification for this issue.

If you find issues by updating the files, please let me know. Hopefully I can find time in the near future to update the plug-in with the newest sources...
