### ISSUE TITLE
Tasks (or links) deleted from DB are displayed on chart after region refresh.

### ISSUE THREAD

**Issue by S-Marek** [ogobrecht/apex-plugin-dhtmlx-gantt#4]
Hi Ottomar,

When task or link is deleted from DB and then the region is refreshed by dynamic action the deleted element is still included on the chart.

When any task property like start date, duration, progress is updated in DB then changes are reflected accordingly on the chart. After deleting, element not simply disappear after refreshing, but is still displayed with values set before deletion.
To rid-off the deleted elements from chart, the whole page have to be reloaded.

I saw the same way in my application and in the demo application. My APEX version is 5.1.2
Is such behavior a bug? It is possible to remove elements deleted from DB using dynamic action?

Thank you for any advice!
Marek

**Comment by ogobrecht** [comment]
Hi Marek,

thank you for your response. I had a short look at my code and have to analyze deeper next weekend. I will you keep updated.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Marek,

I found the relevant info in the API documentation: I have to call `gantt.clearAll();` before pushing new data into the chart - `gantt.parse()` is not enough. I have fixed it already but have to do some documentation for other new features. I will provide tomorrow a new release.

Best regards
Ottmar

**Comment by S-Marek** [comment]
Hi Ottomar,

New version works perfectly. Thank you so much for your support and great plugin!

Best regards,
Marek

**Comment by ogobrecht** [comment]
Hi Marek,

you are welcome :-)

And thanks for closing the issue.

Best regards
Ottmar
