### ISSUE TITLE
Tooltip on dhmtlgantt chart oracle apex plugin

### ISSUE THREAD

**Issue by ShantveerS** [ogobrecht/apex-plugin-dhtmlx-gantt#5]
I used the plugin in my oracle apex application, but it do not show tooltip even though I used 

gantt.templates.tooltip_text = function(start,end,task){
    return "<b>Task:</b> "+task.text+"<br/><b>Start date:</b> " + 
    gantt.templates.tooltip_date_format(start)+ 
    "<br/><b>End date:</b> "+gantt.templates.tooltip_date_format(end);
};

**Comment by ogobrecht** [comment]
Hi ShantveerS,

the new plugin version is out: you can download it [here](https://github.com/ogobrecht/apex-plugin-dhtmlx-gantt/releases/latest).

There is now a new option in the region attributes to configure up to 12 extensions from the dhtmlx library. please check out also the help of the region attributes for more info.

The tooltip is activated in the [online demo app](https://apex.oracle.com/pls/apex/f?p=116612:1), which is also included in the download of the latest plugin release.

Thank you again for your feedback.

Best regards
Ottmar

**Comment by ShantveerS** [comment]
Thank You.. Its working

**Comment by ogobrecht** [comment]
You are welcome :-)
