### ISSUE TITLE
Printing is needed...

### ISSUE THREAD

**Issue by GasparYYC** [ogobrecht/apex-plugin-dhtmlx-gantt#6]
@ogobrecht Not an issue... Just asking if you have considered added the printing capability to your demo app...
In the context of printing, when using the service from DHTMLX you end up sending your data to a service provider (not good in my opinion and also you have to pay for the service).

Would you kindly consider adding printing capabilities to the demo app??

In a previous issue you mentioned it was trivial but I frankly just can't figure out how to..

thank you for your consideration

Note:  v0.7.0 is is great with the tooltips! Thank you.

**Comment by ogobrecht** [comment]
Hi Gaspar,

the demo app is updated with a sample call to the public export API from dhtmlx. Please have a look in the demo app for implementation details (you have to load the API JavaScript in "After Init JS Code"):

- [online demo app](https://apex.oracle.com/pls/apex/f?p=116612:1)
- [download demo app](https://github.com/ogobrecht/apex-plugin-dhtmlx-gantt/releases/download/v0.7.0/demo-app-including-supporting-objects.sql.zip) to inspect the implementation

Hope this helps

Best regards
Ottmar
